// This file was autogenerated by ./bower_components/google-closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/vis/configuration.js', ['vis.Configuration'], [], false);
goog.addDependency('../../../../src/vis/exception.js', ['vis.Exception'], [], false);
goog.addDependency('../../../../src/vis/reflection/reflection-exception.js', ['vis.reflection.ReflectionException'], ['vis.Exception'], false);
goog.addDependency('../../../../src/vis/reflection/reflection.js', ['vis.reflection'], ['vis.reflection.ReflectionException'], false);
goog.addDependency('../../../../src/vis/ui/canvas/scatter-plot.js', ['vis.ui.canvas.ScatterPlot'], ['vis.ui.Visualization'], false);
goog.addDependency('../../../../src/vis/ui/svg/heatmap.js', ['vis.ui.svg.Heatmap'], ['vis.ui.Visualization'], false);
goog.addDependency('../../../../src/vis/ui/svg/scatter-plot.js', ['vis.ui.svg.ScatterPlot'], ['vis.ui.Visualization'], false);
goog.addDependency('../../../../src/vis/ui/ui-exception.js', ['vis.ui.UiException'], ['vis.Exception'], false);
goog.addDependency('../../../../src/vis/ui/visualization-factory.js', ['vis.ui.VisualizationFactory'], ['vis.Configuration', 'vis.reflection', 'vis.ui.UiException', 'vis.ui.Visualization'], false);
goog.addDependency('../../../../src/vis/ui/visualization.js', ['vis.ui.Visualization'], [], false);
goog.addDependency('../../../../src/vis/ui/webgl/scatter-plot.js', ['vis.ui.webgl.ScatterPlot'], ['vis.ui.Visualization'], false);
goog.addDependency('../../../../src/vis/utils/utils.js', ['vis.utils'], [], false);
goog.addDependency('../../../../src/vis/vis.js', ['vis'], ['vis.Configuration', 'vis.ui.Visualization', 'vis.ui.VisualizationFactory'], false);
